version: '3'
services:
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    user-service:
      build: ./user-service
      ports:
        - "8081:8081"
      environment:
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      depends_on:
        - kafka

    order-service:
      build: ./order-service
      ports:
        - "8082:8082"
      environment:
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      depends_on:
        - kafka