spring:
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/sync-service-db
    username: postgres
    password: admin
    hikari:
      schema: sync-service-schema
      connection-timeout: 10000

app:
  jwt:
    secret: "jwtSecret"
    tokenExpiration: 60m
    refreshTokenExpiration: 480m
